Repository kimmccaskill/blucifer-bnb, pull requests merged in 2020-02, with the labels that each got.

#2 Login form
  src/App/App.css
  src/App/App.js
  src/LoginForm/LoginForm.css
  src/LoginForm/LoginForm.js
  src/LoginForm/LoginForm.test.js
Labels: enhancement

#3 Neighborhood cards
  src/App/App.css
  src/App/App.js
  src/AreaCard/AreaCard.css
  src/AreaCard/AreaCard.js
  src/AreaCard/AreaCard.test.js
  src/AreasContainer/AreasContainer.css
  src/AreasContainer/AreasContainer.js
  src/AreasContainer/AreasContainer.test.js
  src/Header/Header.css
  src/Header/Header.js
  src/Header/Header.test.js
  src/LoginForm/LoginForm.js
Labels: enhancement

#4 Login error handling
  src/LoginForm/LoginForm.css
  src/LoginForm/LoginForm.js
Labels: error handling

#5 Area card styling
  src/AreaCard/AreaCard.css
  src/AreaCard/AreaCard.js
  src/AreasContainer/AreasContainer.js
Labels: enhancement

#6 Add routing
  package-lock.json
  package.json
  src/App/App.js
  src/LoginForm/LoginForm.js
  src/index.js
Labels: enhancement

#8 Fetch listings
  src/AreaCard/AreaCard.js
  src/AreasContainer/AreasContainer.js
  src/Listing/Listing.css
  src/Listing/Listing.js
  src/Listing/Listing.test.js
  src/ListingCard/ListingCard.css
  src/ListingCard/ListingCard.js
  src/ListingCard/ListingCard.test.js
  src/ListingsContainer/ListingsContainer.css
  src/ListingsContainer/ListingsContainer.js
  src/ListingsContainer/ListingsContainer.test.js
  src/helpers.js
Labels: enhancement

#11 Display listings
  src/App/App.js
  src/AreaCard/AreaCard.js
  src/AreasContainer/AreasContainer.js
  src/ListingCard/ListingCard.js
  src/ListingsContainer/ListingsContainer.js
Labels: enhancement

#13 Listing detail
  src/App/App.js
  src/AreaCard/AreaCard.js
  src/AreasContainer/AreasContainer.js
  src/Header/Header.js
  src/ListingCard/ListingCard.js
  src/ListingDetails/ListingDetails.css
  src/ListingDetails/ListingDetails.js
  src/ListingDetails/ListingDetails.test.js
  src/ListingsContainer/ListingsContainer.js
Labels: enhancement

#14 Form style
  src/App/App.css
  src/AreaCard/AreaCard.css
  src/AreasContainer/AreasContainer.css
  src/Header/Header.css
  src/Header/Header.js
  src/LoginForm/LoginForm.css
  src/LoginForm/LoginForm.js
  src/assets/Blucifer1.jpg
  src/assets/DarkLogo.png
  src/assets/aerial-bg.jpg
  src/assets/bg-img.jpg
  src/assets/bluciferHERO.jpg
  src/assets/denver-bg.jpeg
Labels: enhancement

#17 Listing details updates
  src/App/App.js
  src/AreaCard/AreaCard.css
  src/AreaCard/AreaCard.js
  src/Header/Header.css
  src/Header/Header.js
  src/ListingCard/ListingCard.js
  src/ListingDetails/ListingDetails.css
  src/ListingDetails/ListingDetails.js
  src/assets/Heart.svg
Labels: enhancement

#18 Areacard test
  src/AreaCard/AreaCard.test.js
  src/Header/__snapshots__/Header.test.js.snap
  src/ListingCard/__snapshots__/ListingCard.test.js.snap
Labels: testing

#19 Favorite functionality
  src/App/App.js
  src/AreaCard/AreaCard.css
  src/Favorites/Favorites.css
  src/Favorites/Favorites.js
  src/Favorites/Favorites.test.js
  src/Header/Header.css
  src/Header/Header.js
  src/ListingCard/ListingCard.css
  src/ListingCard/ListingCard.js
  src/ListingDetails/ListingDetails.css
  src/ListingDetails/ListingDetails.js
Labels: enhancement

#21 Listingdetails testing
  src/App/__snapshots__/App.test.js.snap
  src/Header/__snapshots__/Header.test.js.snap
  src/ListingCard/ListingCard.css
  src/ListingCard/ListingCard.js
  src/ListingCard/__snapshots__/ListingCard.test.js.snap
  src/ListingDetails/ListingDetails.test.js
  src/ListingDetails/__snapshots__/ListingDetails.test.js.snap
  src/ListingsContainer/ListingsContainer.test.js
  src/ListingsContainer/__snapshots__/ListingsContainer.test.js.snap
  src/LoginForm/LoginForm.test.js
  src/LoginForm/__snapshots__/LoginForm.test.js.snap
Labels: testing

#23 Prop types
  package.json
  src/AreaCard/AreaCard.js
  src/Favorites/Favorites.js
  src/Favorites/Favorites.test.js
  src/Favorites/__snapshots__/Favorites.test.js.snap
  src/ListingCard/ListingCard.css
  src/ListingCard/ListingCard.js
  src/ListingCard/__snapshots__/ListingCard.test.js.snap
  src/ListingDetails/ListingDetails.js
  src/ListingDetails/ListingDetails.test.js
  src/ListingsContainer/ListingsContainer.js
  src/LoginForm/LoginForm.js
Labels: enhancement, testing
